steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
  dir: 'ang'
- name: 'gcr.io/cloud-builders/npm'
  args: ['run-script', 'build']
  dir: 'ang'  
- name: 'gcr.io/cloud-builders/mvn'
  args: ['appengine:deploy']
  dir: 'helloworld-springboot'
